### ISSUE TITLE
Asynchronous Support

### ISSUE THREAD

**Issue by Archmonger** [friedelwolff/django-compression-middleware#10]
Django 3.1+ brings support for async middleware which have significantly higher performance than their synchronous counterparts.

It would be nice if this package could support that, assuming async compression libraries exist.

**Comment by friedelwolff** [comment]
Thank you for your interest in the project. I only briefly looked into the matter of asynchronous middleware in Django, and it looked as if django-compression-middleware should work fine without explicit support for async operation. I assume you're not hitting any bugs, right?

Asynchronous support is mainly meant to allow progress on another request while waiting on I/O, and compression is CPU bound. The middleware does not directly send data to the network (other middleware could still process the output of this one before anything is sent). It seems to me that there is no real benefit to providing an explicit asynchronous code path.

However, there is overhead to switching between synchronous and asynchronous middleware and views. Django-compression-middleware is implemented using Django's `MiddlewareMixin`, that should transparently provide support for both modes of operation:
https://docs.djangoproject.com/en/4.0/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware

So as far as I can see, things are already working fine, so for now I'm closing this issue, but feel free to reopen it if I misunderstood or there is a real shortcoming.

**Comment by Archmonger** [comment]
The main benefit is that when Django eventually asyncifies all of its own middleware, it'll result in roughly a 5x improvement in overall webserver performance.

Right now Django is situated as one of the slowest Python web frameworks due to catering to both sync and async code.

See [benchmarks](https://klen.github.io/py-frameworks-bench/) for frameworks such as Blacksheep on what kind of performance is possible with a fully async HTTP stack.

**Comment by friedelwolff** [comment]
My reading of the code suggests that all the built-in middleware in Django already supports async just like django-compression-middleware does (by using `MiddlewareMixin`), so we don't need to wait for Django to asyncify all of its own middleware.

As the documentation suggests, you can check if any middleware (even third party middleware) currently lacks async support:

> you can turn on debug logging for the django.request logger and look for log messages about “Synchronous middleware … adapted”

I strongly doubt that you will see such a 3-5x improvement due to any improvement in middleware. It would only be possible if the middleware was taking the bulk of the time and/or badly blocking other progress.

About the benchmark: I didn't look in detail, but it looks like that benchmark is using Django and Blacksheep with no middleware at all. The performance difference it shows can therefore not be due to differences in middleware. The benchmark runs Django in debug mode, so we shouldn't take it too seriously. Note that Sanic has fully asynchronous middleware, and it doesn't see the big performance improvement over Django you're expecting.

Django is slow for several reasons. I don't know how much of it is due to catering for both sync and async code, but I doubt it is much.
