### ISSUE TITLE
Module can not be found

### ISSUE THREAD

**Issue by KekeliDev** [friedelwolff/django-compression-middleware#11]
After following the documentation and installing the package this is the error I got. 

```
 No module named 'compression_middleware.middleware.CompressionMiddlewaredjango'; 'compression_middleware.middleware' is not a package
```

Mean while I have Installed the packages with provided command

project requirement.txt 

```
#...
zstandard==0.19.0
```

that was the only package added after installation

Also you did say explicitly where the middleware should be... I am beginner these things can be very confusing... the django documentation you referred to did not state explicitly where.

**Comment by friedelwolff** [comment]
It isn't clear to me exactly which steps you followed, so I have to take a few guesses. I assume you use something like a virtual environment where `pip freeze` can tell you which python packages are installed. If the installation of django compression middleware was successful, you should see it in the list, along with zstandard and Brotli.

The error message you give, indicate that the middleware configuration has a typo or some error, since it mentions "CompressionMiddlewaredjango" - review that carefully against the example in the README.

The Django documentation doesn't state exactly where each middleware should be, because it depends somewhat on which middleware you use. I see the link in the README points to the gzip middleware, but the best section is further down on the page:
https://docs.djangoproject.com/en/dev/ref/middleware/#middleware-ordering
That should give you most of the information you need.
